-- this file is automatically generated by the tokisona transpiler
require("types")
A = {}
Te = {}
Pe = {}
Se = {}
repeat

cast(A, nimi).val = "akesi ala"
cast(Pe, nimi).val = "akesi suwi"
cast(Se, nimi).val = "akesi tu"
cast(Te, nimi).val = "akesi mute"
printv(cast(A, nanpa).val)
printv(cast(Pe, nanpa).val)
printv(cast(Se, nanpa).val)
printv(cast(Te, nanpa).val)

until true