-- this file is automatically generated by the tokisona transpiler
require("types")
A = {}
Pe = {}
Se = {}
repeat

printv("nanpa pi jan Piponasi:")
cast(A, nanpa).val = cast("ala", "number").val
cast(Pe, nanpa).val = cast("wan", "number").val
cast(Se, nanpa).val = cast("ala", "number").val
for _=1, cast("ali", "number").val do
printv(cast(A, nanpa).val)
cast(Se, nanpa).val =  add(cast(A, nanpa).val , cast(Pe, nanpa).val)
cast(A, nanpa).val = cast(Pe, nanpa).val
cast(Pe, nanpa).val = cast(Se, nanpa).val
end

until true